// This was auto-generated by sequelize-auto (https://github.com/sequelize/sequelize-auto)
// Somewhat edited due to errors arising from my own naming conventions

var DataTypes = require("sequelize").DataTypes;
var _draftresults = require("./draftresults");
var _leaguesettings = require("./leaguesettings");
var _matchups = require("./matchups");
var _rosterpositions = require("./rosterpositions");
var _sleeperplayers = require("./sleeperplayers");
var _teams = require("./teams");
var _tradeplayers = require("./tradeplayers");
var _trades = require("./trades");
var _users = require("./users");
var _weeklyplayerstats = require("./weeklyplayerstats");

function initModels(sequelize) {
  var draftresults = _draftresults(sequelize, DataTypes);
  var leaguesettings = _leaguesettings(sequelize, DataTypes);
  var matchups = _matchups(sequelize, DataTypes);
  var rosterpositions = _rosterpositions(sequelize, DataTypes);
  var sleeperplayers = _sleeperplayers(sequelize, DataTypes);
  var teams = _teams(sequelize, DataTypes);
  var tradeplayers = _tradeplayers(sequelize, DataTypes);
  var trades = _trades(sequelize, DataTypes);
  var users = _users(sequelize, DataTypes);
  var weeklyplayerstats = _weeklyplayerstats(sequelize, DataTypes);

  sleeperplayers.belongsTo(rosterpositions, { as: "rosterPosition", foreignKey: "rosterPositionId"});
  rosterpositions.hasMany(sleeperplayers, { as: "sleeperplayers", foreignKey: "rosterPositionId"});
  weeklyplayerstats.belongsTo(rosterpositions, { as: "rosterPosition", foreignKey: "rosterPositionId"});
  rosterpositions.hasMany(weeklyplayerstats, { as: "weeklyplayerstats", foreignKey: "rosterPositionId"});
  draftresults.belongsTo(teams, { as: "draftTeam", foreignKey: "teamId"});
  teams.hasMany(draftresults, { as: "draftresults", foreignKey: "teamId"});
  matchups.belongsTo(teams, { as: "opponent", foreignKey: "opponentId"});
  teams.hasMany(matchups, { as: "matchups", foreignKey: "opponentId"});
  matchups.belongsTo(teams, { as: "team", foreignKey: "teamId"});
  teams.hasMany(matchups, { as: "team_matchups", foreignKey: "teamId"});
  tradeplayers.belongsTo(teams, { as: "newTeam", foreignKey: "newTeamId"});
  teams.hasMany(tradeplayers, { as: "tradeplayers", foreignKey: "newTeamId"});
  tradeplayers.belongsTo(teams, { as: "originalTeam", foreignKey: "originalTeamId"});
  teams.hasMany(tradeplayers, { as: "originalTeam_tradeplayers", foreignKey: "originalTeamId"});
  trades.belongsTo(teams, { as: "team1_team", foreignKey: "team1"});
  teams.hasMany(trades, { as: "trades", foreignKey: "team1"});
  trades.belongsTo(teams, { as: "team2_team", foreignKey: "team2"});
  teams.hasMany(trades, { as: "team2_trades", foreignKey: "team2"});
  weeklyplayerstats.belongsTo(teams, { as: "fantasyTeam", foreignKey: "teamId"});
  teams.hasMany(weeklyplayerstats, { as: "weeklyplayerstats", foreignKey: "teamId"});
  teams.belongsTo(users, { as: "user", foreignKey: "userId"});
  users.hasMany(teams, { as: "teams", foreignKey: "userId"});

  return {
    draftresults,
    leaguesettings,
    matchups,
    rosterpositions,
    sleeperplayers,
    teams,
    tradeplayers,
    trades,
    users,
    weeklyplayerstats,
  };
}
module.exports = initModels;
module.exports.initModels = initModels;
module.exports.default = initModels;
